### ISSUE TITLE
Test and examples for nlmixr2

### ISSUE THREAD

**Issue by michielve** [RichardHooijmaijers/nlmixr.docker#8]
Hello Richard,

It seems that both example scripts in the prod.nlmixr2 folder still use nlmixr and rxODE and the /test_install.R script in the Readme is still based on an old R version, therefore giving an error.

Could you let me know if updated files are available.

Thank you

Michiel

**Comment by RichardHooijmaijers** [comment]
Hi @michielve

Sorry it took a while. I adapted the example script as suggested. With respect to the test_install script; this is a bit obsolete. With initial versions of the package, there was a python dependency which made the installation process more difficult. Because the current version installs like any other R package, this test is no longer used. Therefore I removed it from the documentation.
